package ru.project.web.entities;

// default package
// Generated 23.10.2017 10:46:27 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

    private Long id;
    private Author author;
    private Genre genre;
    private Publisher publisher;
    private String name;
    private byte[] content;
    private int pageCount;
    private String isbn;
    private int publishYear;
    private byte[] image;
    private String descr;
    private Integer rating;
    private Long voteCount;
    private Set<Vote> votes = new HashSet<Vote>(0);

    public Book() {
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount,
	    String isbn, int publishYear) {
	this.author = author;
	this.genre = genre;
	this.publisher = publisher;
	this.name = name;
	this.content = content;
	this.pageCount = pageCount;
	this.isbn = isbn;
	this.publishYear = publishYear;
    }

    public Book(Author author, Genre genre, Publisher publisher, String name, byte[] content, int pageCount,
	    String isbn, int publishYear, byte[] image, String descr, Integer rating, Long voteCount, Set<Vote> votes) {
	this.author = author;
	this.genre = genre;
	this.publisher = publisher;
	this.name = name;
	this.content = content;
	this.pageCount = pageCount;
	this.isbn = isbn;
	this.publishYear = publishYear;
	this.image = image;
	this.descr = descr;
	this.rating = rating;
	this.voteCount = voteCount;
	this.votes = votes;
    }

    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    public Author getAuthor() {
	return this.author;
    }

    public void setAuthor(Author author) {
	this.author = author;
    }

    public Genre getGenre() {
	return this.genre;
    }

    public void setGenre(Genre genre) {
	this.genre = genre;
    }

    public Publisher getPublisher() {
	return this.publisher;
    }

    public void setPublisher(Publisher publisher) {
	this.publisher = publisher;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public byte[] getContent() {
	return this.content;
    }

    public void setContent(byte[] content) {
	this.content = content;
    }

    public int getPageCount() {
	return this.pageCount;
    }

    public void setPageCount(int pageCount) {
	this.pageCount = pageCount;
    }

    public String getIsbn() {
	return this.isbn;
    }

    public void setIsbn(String isbn) {
	this.isbn = isbn;
    }

    public int getPublishYear() {
	return this.publishYear;
    }

    public void setPublishYear(int publishYear) {
	this.publishYear = publishYear;
    }

    public byte[] getImage() {
	return this.image;
    }

    public void setImage(byte[] image) {
	this.image = image;
    }

    public String getDescr() {
	return this.descr;
    }

    public void setDescr(String descr) {
	this.descr = descr;
    }

    public Integer getRating() {
	return this.rating;
    }

    public void setRating(Integer rating) {
	this.rating = rating;
    }

    public Long getVoteCount() {
	return this.voteCount;
    }

    public void setVoteCount(Long voteCount) {
	this.voteCount = voteCount;
    }

    public Set<Vote> getVotes() {
	return this.votes;
    }

    public void setVotes(Set<Vote> votes) {
	this.votes = votes;
    }

}
