package ru.project.web.entities;

// default package
// Generated 23.10.2017 10:46:27 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable {

    private Long id;
    private Genre genre;
    private String name;
    private Set<Book> books = new HashSet<Book>(0);
    private Set<Genre> genres = new HashSet<Genre>(0);

    public Genre() {
    }

    public Genre(String name) {
	this.name = name;
    }

    public Genre(Genre genre, String name, Set<Book> books, Set<Genre> genres) {
	this.genre = genre;
	this.name = name;
	this.books = books;
	this.genres = genres;
    }

    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    public Genre getGenre() {
	return this.genre;
    }

    public void setGenre(Genre genre) {
	this.genre = genre;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public Set<Book> getBooks() {
	return this.books;
    }

    public void setBooks(Set<Book> books) {
	this.books = books;
    }

    public Set<Genre> getGenres() {
	return this.genres;
    }

    public void setGenres(Set<Genre> genres) {
	this.genres = genres;
    }

}
