package ru.project.web.entities;

// default package
// Generated 23.10.2017 10:46:27 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher implements java.io.Serializable {

    private Long id;
    private String name;
    private Set<Book> books = new HashSet<Book>(0);

    public Publisher() {
    }

    public Publisher(String name) {
	this.name = name;
    }

    public Publisher(String name, Set<Book> books) {
	this.name = name;
	this.books = books;
    }

    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public Set<Book> getBooks() {
	return this.books;
    }

    public void setBooks(Set<Book> books) {
	this.books = books;
    }

}
